name: Daily Bun Script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Script
        run: bun run src/index.ts 
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOGIN_PATH: ${{ secrets.LOGIN_PATH }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

      - name: Send Discord Webhook on Success
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"✅ 【Login Supabase】Complete, Status: 呵欠是gay!!!!!!!!!!!!!!!!!!!!!\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send Discord Webhook on Failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"❌ 【Login Supabase】Fail, Please check github action status\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
